// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// IMPORTANT: Replace these values with your actual Firebase configuration
/// You can get these values from:
/// 1. Firebase Console -> Project Settings -> General
/// 2. Or run: flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEOMvl5R652nQEULdzbRhY987g3Ok1IkQ',
    appId: '1:927400788077:web:8b4f7a72357246b5bd7f64',
    messagingSenderId: '927400788077',
    projectId: 'mymenu-8236d',
    authDomain: 'mymenu-8236d.firebaseapp.com',
    storageBucket: 'mymenu-8236d.firebasestorage.app',
    measurementId: 'G-9S9MZBJWJD',
  );

  // Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: '927400788077',
    projectId: 'mymenu-8236d',
    storageBucket: 'mymenu-8236d.firebasestorage.app',
  );

  // iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '927400788077',
    projectId: 'mymenu-8236d',
    storageBucket: 'mymenu-8236d.firebasestorage.app',
    iosBundleId: 'com.example.restaurantMenu',
  );

  // macOS configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '927400788077',
    projectId: 'mymenu-8236d',
    storageBucket: 'mymenu-8236d.firebasestorage.app',
    iosBundleId: 'com.example.restaurantMenu.RunnerTests',
  );

  // Windows configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: '927400788077',
    projectId: 'mymenu-8236d',
    authDomain: 'mymenu-8236d.firebaseapp.com',
    storageBucket: 'mymenu-8236d.firebasestorage.app',
  );
}

// Configuration values for mymenu-8236d project:
//
// ✅ Web Configuration (CONFIGURED):
// - API Key: AIzaSyCEOMvl5R652nQEULdzbRhY987g3Ok1IkQ
// - App ID: 1:927400788077:web:8b4f7a72357246b5bd7f64
// - Messaging Sender ID: 927400788077
// - Project ID: mymenu-8236d
// - Auth Domain: mymenu-8236d.firebaseapp.com
// - Storage Bucket: mymenu-8236d.firebasestorage.app
// - Measurement ID: G-9S9MZBJWJD
//
// ⚠️ Other Platforms (Android/iOS/macOS/Windows):
// If you need to support other platforms, you need to:
// 1. Go to Firebase Console (https://console.firebase.google.com)
// 2. Select your project (mymenu-8236d)
// 3. Click "Add app" and select the platform
// 4. Follow the setup wizard to get API Key and App ID for that platform
// 5. Update the corresponding configuration above
//
// Or run: flutterfire configure